module.exports = {
  "@layout-body-background": "#252423",
  "@layout-header-background": "#201f1e",
  "@text-color": "fade(@white, 90%)",
  "@text-color-secondary": "fade(@white, 55%)",
  "@text-color-inverse": "@white",
  "@icon-color-hover": "fade(@white, 80%)",
  "@heading-color": "fade(@white, 90%)",
  "@component-background": "#292827",
  "@layout-trigger-background-light": "@layout-trigger-background",
  "@btn-primary-bg": "darken(@primary-color, 9%)",
  "@btn-danger-bg": "darken(@error-color, 6%)",
  "@btn-danger-border": "@btn-danger-bg",
  "@layout-sider-background-light": "@menu-bg",
  "@menu-dark-bg": "@layout-header-background",
  "@menu-dark-submenu-bg": "@component-background",
  "@menu-dark-item-active-bg": "fade(@primary-color, 30%)",
  "@input-bg": "#201f1ec4",
  "@btn-default-bg": "@input-bg",
  "@select-background": "#201f1e",
  "@select-dropdown-bg": "#201f1e",
  "@table-selected-row-bg": "@menu-dark-item-active-bg",
  "@table-row-hover-bg": "@menu-dark-item-active-bg",
  "@table-expanded-row-bg": "@input-bg",
  "@shadow-color": "rgba(0, 0, 0, 0.8)",
  "@border-radius-base": "4px",
  "@popover-background": "@component-background",
  "@slider-rail-background-color-hover": "@border-color-split",
  "@layout-trigger-background": "@menu-dark-bg",
  "@layout-trigger-color": "fade(#fff, 80%)"
};
